BazarMVC/Controllers/CompradorController.cs
using Bazar.Class;
using Bazar.Interface;
using BazarMVC.Repositories.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using static BazarMVC.Models.CompradorViewModels;

namespace BazarMVC.Controllers
{
    [Authorize]
    public class CompradorController : Controller
    {
        // GET: Comprador
        public ActionResult Index()
        {
            List<CompradorModel> listaCompradores = new List<CompradorModel>();
            InterfaceBazar bazar = new InterfaceBazar();
            var getCompradores = bazar.GetCompradores();
            if (!getCompradores.ProccessOk)
            {
                return View(listaCompradores);
            }
            foreach (var item in getCompradores.ListaComprador)
            {
                CompradorModel comprador = new CompradorModel();
                comprador.Id = item.Id;
                comprador.Nome = item.Nome;
                comprador.Sobrenome = item.Sobrenome;
                listaCompradores.Add(comprador);
            }
            return View(listaCompradores);
        }

        // GET: Comprador/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Comprador/Create
        public ActionResult Create()
        {
            return View(new CompradorCreateViewModel());
        }

        // POST: Comprador/Create
        [HttpPost]
        public ActionResult Create(CompradorCreateViewModel model)
        {
            InterfaceBazar bazar = new InterfaceBazar();
            try
            {
                Comprador comprador = new Comprador();
                comprador.Nome = model.Nome;
                comprador.Sobrenome = model.Sobrenome;
                var adicionarComprador = bazar.AdicionarComprador(comprador);
                if (!adicionarComprador.ProccessOk)
                {
                    return View(model);
                }

                TempData["MensagemSucesso"] = "Comprador cadastrado com sucesso!";
                return RedirectToAction("Index");
            }
            catch
            {
                return View(model);
            }
        }

        // GET: Comprador/Edit/5
        public ActionResult Edit(int id = 0)
        {
            if(id == 0)
            {
                TempData["MensagemErro"] = "Erro ao Carregar Comprador";
                return RedirectToAction("Index");
            }
            InterfaceBazar bazar = new InterfaceBazar();
            CompradorEditViewModel model = new CompradorEditViewModel();
            var comprador = bazar.GetComprador(id);
            if (!comprador.ProccessOk)
            {
                TempData["MensagemErro"] = "Erro ao Carregar Comprador";
                return RedirectToAction("Index");
            }
            model.Id = comprador.Comprador.Id;
            model.Nome = comprador.Comprador.Nome;
            model.Sobrenome = comprador.Comprador.Sobrenome;
            return View(model);
        }

        // POST: Comprador/Edit/5
        [HttpPost]
        public ActionResult Edit(CompradorEditViewModel model)
        {
            try
            {
                InterfaceBazar bazar = new InterfaceBazar();
                Comprador comprador = new Comprador();
                comprador.Id = model.Id;
                comprador.Nome = model.Nome;
                comprador.Sobrenome = model.Sobrenome;
                var salvarComprador = bazar.EditarComprador(comprador);
                if (!salvarComprador.ProccessOk)
                {
                    TempData["MensagemErro"] = "Erro ao salvar o Comprador";
                    return View(model);
                }

                return RedirectToAction("Index");
            }
            catch
            {
                TempData["MensagemErro"] = "Erro Inesperado";
                return View(model);
            }
        }

        // GET: Comprador/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Comprador/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

BazarMVC/Controllers/HomeController.cs
using Bazar.Interface;
using Bazar.Result;
using BazarMVC.Repositories;
using BazarMVC.Repositories.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BazarMVC.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            HomeModel model = new HomeModel();
            InterfaceBazar bazar = new InterfaceBazar();
            EstatisticaResult estatisticas = new EstatisticaResult();
            if (User.IsInRole("Admin"))
            {
                estatisticas = bazar.GetEstatisticas();
                if (!estatisticas.ProccessOk)
                {
                    ViewBag.MensagemErro = "Erro ao Capturar Estatísticas";
                    return View(model);
                }
            }
            else
            {
                var user = new AspNetUsersRepository().GetUsuarioByUsername(User.Identity.Name);
                var getVendedor = bazar.GetVendedorByIdUser(user.Id);
                estatisticas = bazar.GetEstatisticas(getVendedor.Vendedor.Id);
                if (!estatisticas.ProccessOk)
                {
                    ViewBag.MensagemErro = "Erro ao Capturar Estatísticas";
                    return View(model);
                }
            }
            model.Compradores = estatisticas.Compradores;
            model.Produtos = estatisticas.Produtos;
            if(estatisticas.ProdutosPagos != 0 && estatisticas.ProdutosVendidos != 0)
                model.ProdutosPagos = (100 * estatisticas.ProdutosPagos) / estatisticas.ProdutosVendidos;
            model.ProdutosVendidos = estatisticas.ProdutosVendidos;
            model.Vendas = estatisticas.Vendas;
            model.Vendedores = estatisticas.Vendedores;
            return View(model);
        }
    }
}

BazarMVC/Controllers/VendasController.cs
using Bazar.Class;
using Bazar.Interface;
using BazarMVC.Repositories;
using BazarMVC.Repositories.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using static BazarMVC.Models.VendasViewModels;

namespace BazarMVC.Controllers
{
    [Authorize]
    public class VendasController : Controller
    {
        // GET: Vendas
        public ActionResult Index()
        {
            List<VendasModel> listaVendas = new List<VendasModel>();
            InterfaceBazar bazar = new InterfaceBazar();
            var getVendas = bazar.GetVendas();
            if (!getVendas.ProccessOk)
            {
                return View(listaVendas);
            }
            foreach (var item in getVendas.ListaVenda)
            {
                VendasModel vendas = new VendasModel();
                vendas.Id = item.Id;
                vendas.ValorTotal = item.ValorTotal;
                var nomeComprador = bazar.GetComprador(item.IdComprador);
                if (!nomeComprador.ProccessOk)
                {
                    return View(listaVendas);
                }
                vendas.Comprador = nomeComprador.Comprador.Nome + " " + nomeComprador.Comprador.Sobrenome;
                listaVendas.Add(vendas);
            }
            return View(listaVendas);
        }

        // GET: Vendas/Details/5
        public ActionResult Details(int id = 0)
        {
            if(id == 0)
            {
                TempData["MensagemErro"] = "Venda não existe!";
                return RedirectToAction("Index");
            }
            VendasDetailsViewModel model = new VendasDetailsViewModel();
            InterfaceBazar bazar = new InterfaceBazar();
            var getVendas = bazar.GetVenda(id);
            if (!getVendas.ProccessOk)
            {
                TempData["MensagemErro"] = "Erro ao capturar venda!";
                return RedirectToAction("Index");
            }
            model.Id = getVendas.Venda.Id;
            model.ValorTotal = getVendas.Venda.ValorTotal;
            var comprador = bazar.GetComprador(getVendas.Venda.IdComprador);
            if (!comprador.ProccessOk)
            {
                TempData["MensagemErro"] = "Erro ao capturar comprador da venda!";
                return RedirectToAction("Index");
            }
            model.NomeComprador = comprador.Comprador.Nome + " " + comprador.Comprador.Sobrenome;
            foreach (var item in getVendas.Venda.ListaProdutoVendido)
            {
                ProdutosVendidosModel produto = new ProdutosVendidosModel();
                produto.Id = item.Id;
                produto.PrecoPago = item.PrecoPago;
                var getProduto = bazar.GetProduto(item.IdProduto);
                if (!getProduto.ProccessOk)
                {
                    TempData["MensagemErro"] = "Erro ao capturar produto da venda!";
                    return RedirectToAction("Index");
                }
                produto.Produto = getProduto.Produto.Nome;
                produto.Quantidade = item.Quantidade;
                produto.Status = item.Status;
                var getVendedor = bazar.GetVendedor(getProduto.Produto.IdVendedor);
                if (!getVendedor.ProccessOk)
                {
                    TempData["MensagemErro"] = "Erro ao capturar vendedor do produto!";
                    return RedirectToAction("Index");
                }
                try
                {
                    var getUser = new AspNetUsersRepository().GetUsuario(getVendedor.Vendedor.IdUser);
                    produto.Vendedor = getUser.Nome + " " + getUser.Sobrenome;
                }
                catch (Exception ex)
                {
                    TempData["MensagemErro"] = "Erro ao capturar nome do vendedor do produto!";
                    return RedirectToAction("Index");
                }
                model.ListaProdutos.Add(produto);
            }
            return View(model);
        }

        // GET: Vendas/Create
        public ActionResult Create()
        {
            InterfaceBazar bazar = new InterfaceBazar();
            VendasCreateViewModel model = new VendasCreateViewModel();
            var compradores = bazar.GetCompradores();
            if (!compradores.ProccessOk)
            {
                return View(model);
            }
            foreach (var item in compradores.ListaComprador)
            {
                CompradorModel comprador = new CompradorModel();
                comprador.Id = item.Id;
                comprador.Nome = item.Nome;
                comprador.Sobrenome = item.Sobrenome;
                model.ListaCompradores.Add(comprador);
            }

            var produtos = bazar.GetProdutos();
            if (!produtos.ProccessOk)
            {
                return View(model);
            }
            foreach (var item in produtos.ListaProduto)
            {
                if(item.Quantidade < 1)
                {
                    continue;
                }
                ProdutosModel produto = new ProdutosModel();
                produto.Id = item.Id;
                produto.Nome = item.Nome;
                produto.Preco = item.Preco;
                produto.Quantidade = item.Quantidade;
                var vendedor = bazar.GetVendedor(item.IdVendedor);
                if (!produtos.ProccessOk)
                {
                    return View(model);
                }
                //produto.Vendedor = vendedor.Vendedor.Nome;
                produto.IdVendedor = vendedor.Vendedor.Id;
                model.ListaProdutos.Add(produto);
            }

            return View(model);
        }

        // POST: Vendas/Create
        [HttpPost]
        public ActionResult Create(VendasCreateViewModel model)
        {
            InterfaceBazar bazar = new InterfaceBazar();

            //Botão Cadastrar
            if (model.ProdutoSelecionado == 0)
            {
                Venda venda = new Venda();
                List<ProdutoVendido> listaProdutos = new List<ProdutoVendido>();
                if (model.Comprador == null)
                {
                    return View(model);
                }
                venda.IdComprador = int.Parse(model.Comprador);
                foreach (var item in model.ListaProdutosEscolhidos)
                {
                    ProdutoVendido produto = new ProdutoVendido();
                    produto.IdProduto = item.Id;
                    produto.PrecoPago = item.Preco;
                    produto.Quantidade = item.Quantidade;
                    listaProdutos.Add(produto);
                }

                venda.ValorTotal = model.ValorTotal;
                venda.ListaProdutoVendido = listaProdutos;
                var cadastroVenda = bazar.AdicionarVenda(venda);
                if (!cadastroVenda.ProccessOk)
                {
                    return View(model);
                }

                foreach (var item in listaProdutos)
                {
                    ProdutoVendido produtoVendido = new ProdutoVendido();
                    item.Quantidade = 1;
                    var produto = bazar.GetProduto(item.IdProduto);
                    if (!produto.ProccessOk)
                    {
                        return View(model);
                    }
                    
                    var diminuirProduto = bazar.DiminuirQuantidadeProduto(produto.Produto, item.Quantidade);
                }

                TempData["MensagemSucesso"] = "Venda cadastrada com sucesso!";
                return RedirectToAction("Index");
            }
            else
            {
                int quantidadeFront = 1;
                // Adicionar da Lista de Compras
                if (model.ListaProdutos.Any(x => x.Id == model.ProdutoSelecionado))
                {
                    var produto = model.ListaProdutos.Where(a => a.Id == model.ProdutoSelecionado).ToList().First();
                    produto.Quantidade = quantidadeFront;
                    model.ListaProdutos.Remove(produto);
                    model.ListaProdutosEscolhidos.Add(produto);
                    model.ValorTotal += produto.Preco;
                }
                //Removar da Lista de Compras
                else
                {
                    var produto = model.ListaProdutosEscolhidos.Where(a => a.Id == model.ProdutoSelecionado).ToList().First();
                    produto.Quantidade = quantidadeFront;
                    model.ListaProdutos.Add(produto);
                    model.ListaProdutosEscolhidos.Remove(produto);
                    model.ValorTotal -= produto.Preco;
                }

                ModelState.Clear();

                return View(model);
            }
        }

        #region depois
        // GET: Vendas/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Vendas/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Vendas/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Vendas/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        #endregion

        public ActionResult ListarProdutos(string id)
        {
            InterfaceBazar bazar = new InterfaceBazar();
            Venda venda = new Venda();

BazarMVC/Views/Home/Index.cshtml
@model BazarMVC.Repositories.Model.HomeModel

@{
    ViewBag.Title = "Home";
}

<!-- Content Header (Page header) -->
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0 text-dark">Dashboard</h1>
                @if (!string.IsNullOrEmpty(ViewBag.MensagemErro))
                {
                    <span>Erro ao capturar informações</span>
                }
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->
<!-- Main content -->
<section class="content">
    <div class="container-fluid">
        <!-- Small boxes (Stat box) -->
        @if (User.IsInRole("Admin"))
        {
            <div class="row">
                <div class="col-lg-4 col-6">
                    <!-- small box -->
                    <div class="small-box bg-info">
                        <div class="inner">
                            <h3>@Model.Vendas</h3>

                            <p>Vendas</p>
                        </div>
                        <div class="icon">
                            <i class="fas fa-chart-line"></i>
                        </div>
                        <a href="@Url.Action("Index", "Vendas")" class="small-box-footer">Mais Informações <i class="fas fa-arrow-circle-right"></i></a>
                    </div>
                </div>
                <!-- ./col -->
                <div class="col-lg-4 col-6">
                    <!-- small box -->
                    <div class="small-box bg-success">
                        <div class="inner">
                            <h3>@Model.Produtos</h3>

                            <p>Produtos</p>
                        </div>
                        <div class="icon">
                            <i class="fas fa-shopping-cart"></i>
                        </div>
                        <a href="@Url.Action("Index", "Produtos")" class="small-box-footer">Mais Informações <i class="fas fa-arrow-circle-right"></i></a>
                    </div>
                </div>
                <!-- ./col -->
                <div class="col-lg-4 col-6">
                    <!-- small box -->
                    <div class="small-box bg-warning">
                        <div class="inner">
                            <h3>@Model.ProdutosVendidos</h3>

                            <p>Produtos Vendidos</p>
                        </div>
                        <div class="icon">
                            <i class="fas fa-cart-arrow-down"></i>
                        </div>
                        <a href="@Url.Action("Index", "ProdutosVendidos")" class="small-box-footer">Mais Informações <i class="fas fa-arrow-circle-right"></i></a>
                    </div>
                </div>
                <div class="col-lg-4 col-6">
                    <!-- small box -->
                    <div class="small-box bg-info">
                        <div class="inner">
                            <h3>@Model.Compradores</h3>

                            <p>Compradores</p>
                        </div>
                        <div class="icon">
                            <i class="fas fa-user"></i>
                        </div>
                        <a href="@Url.Action("Index", "Comprador")" class="small-box-footer">Mais Informações <i class="fas fa-arrow-circle-right"></i></a>
                    </div>
                </div>
                <!-- ./col -->
                <div class="col-lg-4 col-6">
                    <!-- small box -->
                    <div class="small-box bg-success">
                        <div class="inner">
                            <h3>@Model.Vendedores</h3>

                            <p>Vendedores</p>
                        </div>
                        <div class="icon">
                            <i class="fas fa-store"></i>
                        </div>
                        <a href="@Url.Action("Index", "Vendedor")" class="small-box-footer">Mais Informações <i class="fas fa-arrow-circle-right"></i></a>
                    </div>
                </div>
                <!-- ./col -->
                <div class="col-lg-4 col-6">
                    <!-- small box -->
                    <div class="small-box bg-warning">
                        <div class="inner">
                            <h3>@Model.ProdutosPagos<sup style="font-size: 20px">%</sup></h3>

                            <p>Produtos Pagos</p>
                        </div>
                        <div class="icon">
                            <i class="fas fa-balance-scale"></i>
                        </div>
                        <a href="@Url.Action("Index", "ProdutosVendidos")" class="small-box-footer">Mais Informações <i class="fas fa-arrow-circle-right"></i></a>
                    </div>
                </div>
            </div>
        }
        else
        {
            <div class="row">
                <div class="col-lg-4 col-6">
                    <div class="small-box bg-info">
                        <div class="inner">
                            <h3>@Model.Produtos</h3>

                            <p>Produtos</p>
                        </div>
                        <div class="icon">
                            <i class="fas fa-shopping-cart"></i>
                        </div>
                        <a href="@Url.Action("Index", "Produtos")" class="small-box-footer">Mais Informações <i class="fas fa-arrow-circle-right"></i></a>
                    </div>
                </div>
                <div class="col-lg-4 col-6">
                    <div class="small-box bg-success">
                        <div class="inner">
                            <h3>@Model.ProdutosVendidos</h3>

                            <p>Produtos Vendidos</p>
                        </div>
                        <div class="icon">
                            <i class="fas fa-cart-arrow-down"></i>
                        </div>
                        <a href="@Url.Action("Index", "ProdutosVendidos")" class="small-box-footer">Mais Informações <i class="fas fa-arrow-circle-right"></i></a>
                    </div>
                </div>
                <div class="col-lg-4 col-6">
                    <div class="small-box bg-warning">
                        <div class="inner">
                            <h3>@Model.ProdutosPagos<sup style="font-size: 20px">%</sup></h3>

                            <p>Produtos Pagos</p>
                        </div>
                        <div class="icon">
                            <i class="fas fa-balance-scale"></i>
                        </div>
                        <a href="@Url.Action("Index", "ProdutosVendidos")" class="small-box-footer">Mais Informações <i class="fas fa-arrow-circle-right"></i></a>
                    </div>
                </div>
            </div>
        }
    </div>
</section>